version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@leliadoura.com
      PGADMIN_DEFAULT_PASSWORD: Abc123.
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge